/**
 * Derivations for /safety.
 *
 * All figures come from src/data/safety-data.json, which is generated by
 * scripts/generate-safety-data.py from four public sources (Gallup World Poll,
 * UNODC via Our World in Data, and the U.S. State Department advisory feed).
 * Nothing is computed here that isn't arithmetic on that file; tests in
 * safety.test.ts pin the headline numbers so silent drift fails CI.
 *
 * The organising idea: a country's *felt* safety and its *recorded* homicide
 * rate are separate measurements, and the interesting quantity is the gap.
 * `residual` is that gap in percentage points — how much safer (or less safe)
 * people feel than the fitted relationship predicts from the body count alone.
 * A positive residual is not automatically bias: violence concentrated away
 * from most residents produces one too.
 */

import DATA from '../data/safety-data.json';

export interface Advisory {
  level: number;
  label: string;
  issued: string | null;
  link: string | null;
  /** Set when one advisory covers several countries. */
  covers: string | null;
}

export interface HomicidePoint {
  year: number;
  rate: number;
}

export interface Country {
  country: string;
  /** % answering yes to "Do you feel safe walking alone at night?" (2024). */
  feltSafe: number;
  /** Gallup Law and Order Index, 0-100 (2024 field year). */
  lawOrder: number | null;
  /** Same index, 2023 field year — the only measure with a prior-year table. */
  lawOrderPrev: number | null;
  /** UNODC intentional homicides per 100k, most recent year >= 2015. */
  homicide: number | null;
  homicideYear: number | null;
  homicideSeries: HomicidePoint[];
  /** Felt-safe % the fit predicts from this homicide rate. */
  predicted: number | null;
  /** feltSafe - predicted, in percentage points. */
  residual: number | null;
  advisory: Advisory | null;
}

export interface Fit {
  n: number;
  r: number;
  r2: number;
  spearman: number;
  slope: number;
  intercept: number;
  form: string;
}

export const COUNTRIES = DATA.countries as Country[];
export const FIT = DATA.fit as Fit;
export const META = DATA.meta;
export const GLOBAL_TREND = DATA.globalTrend;
export const TRAVELER_DEATH_CAUSES = DATA.travelerDeathCauses;
export const GLOBAL_VICTIMIZATION = DATA.globalVictimization;
export const ADVISORY_LEVEL_COUNTS = DATA.advisoryLevelCounts as Record<string, number>;

export const ADVISORY_LABELS: Record<number, string> = {
  1: 'Exercise normal precautions',
  2: 'Exercise increased caution',
  3: 'Reconsider travel',
  4: 'Do not travel',
};

/** Countries carrying both measurements — the only ones the fit can speak to. */
export const FITTED: Country[] = COUNTRIES.filter(
  (c) => c.homicide !== null && c.residual !== null,
);

export function byName(name: string): Country | undefined {
  return COUNTRIES.find((c) => c.country === name);
}

/** Predicted felt-safe % at a given homicide rate, per the committed fit. */
export function predictFelt(homicide: number): number {
  return FIT.intercept + FIT.slope * Math.log10(homicide + 0.1);
}

export function topBy<K extends keyof Country>(
  key: K,
  n: number,
  dir: 'asc' | 'desc' = 'desc',
  pool: Country[] = COUNTRIES,
): Country[] {
  const rows = pool.filter((c) => c[key] !== null && c[key] !== undefined);
  const sorted = [...rows].sort((a, b) => {
    const av = a[key] as unknown as number;
    const bv = b[key] as unknown as number;
    return dir === 'desc' ? bv - av : av - bv;
  });
  return sorted.slice(0, n);
}

/** Year-over-year change in the Law and Order Index, where both years exist. */
export function lawOrderChange(c: Country): number | null {
  if (c.lawOrder === null || c.lawOrderPrev === null) return null;
  return c.lawOrder - c.lawOrderPrev;
}

/** Change in homicide rate between the earliest year >= `from` and the latest. */
export function homicideChange(
  c: Country,
  from = 2010,
): { first: HomicidePoint; last: HomicidePoint; ratio: number } | null {
  const pts = c.homicideSeries.filter((p) => p.year >= from);
  if (pts.length < 2) return null;
  const first = pts[0];
  const last = pts[pts.length - 1];
  if (first.rate <= 0) return null;
  return { first, last, ratio: last.rate / first.rate };
}

export const fmtPct = (v: number): string => `${Math.round(v)}%`;
export const fmtRate = (v: number): string =>
  v >= 10 ? v.toFixed(0) : v.toFixed(v < 1 ? 2 : 1);
export const fmtSigned = (v: number): string =>
  `${v > 0 ? '+' : v < 0 ? '−' : ''}${Math.abs(v).toFixed(1)}`;
